import {Markdown} from '@mfng/shared-app/markdown.js';
import * as React from 'react';

const welcomeText = `
This demo showcases a chat assistant capable of displaying images of various
kinds.

Built using [MFNG](https://github.com/unstubbable/mfng/) — a minimal React
Server Components (RSC) bundler/library — and the
[Vercel AI SDK](https://sdk.vercel.ai/docs), this demo leverages RSCs to
seamlessly integrate text with UI, as generated by the LLM.

The app is deployed on AWS Lambda & CloudFront. Due to cost considerations, it
is heavily rate-limited, which may result in occasional error responses.

Give it a try with an example:
`;

const examplePrompts = [
  `Pick a painter from the 18th century and show me some of their work.`,
  `List some of the earliest photographs.`,
  `What are those funny-looking, furless cats called?`,
];

export function Welcome(): React.ReactNode {
  return (
    <div className="rounded-lg bg-white p-4 text-zinc-500 shadow md:p-6">
      <h3 className="mb-4 text-lg font-bold leading-6 text-black">
        Welcome to the MFNG AI SDK Generative UI demo!
      </h3>
      <Markdown text={welcomeText} />
      <ul className="space-y-3">
        {examplePrompts.map((prompt) => (
          <li key={prompt} className="ml-4 list-item list-disc">
            <button className="text-left" name="example-prompt" value={prompt}>
              <span className="text-black underline">{prompt}</span>
            </button>
          </li>
        ))}
      </ul>
    </div>
  );
}
