name = "mfng"
main = "../../dist/worker.js"
compatibility_date = "2023-02-21"
compatibility_flags = ["nodejs_compat"]

[dev]
port = 3000

# Deactivate build command to prevent wrangler from restarting the build on any
# code change. Instead we start the build separately (in watch mode).
[build]
command = ""
watch_dir = []

[assets]
bucket = "../../dist"
include = ["client", "react-server-manifest.json"]
serve_single_page_app = true
