name = "mfng"
main = "../../dist/worker/index.js"
compatibility_date = "2024-03-04"
compatibility_flags = ["nodejs_als"]

[dev]
port = 3000

# Deactivate build command to prevent wrangler from restarting the build on any
# code change. Instead we start the build separately (in watch mode).
[build]
command = ""
watch_dir = []

[assets]
bucket = "../../dist/static"
serve_single_page_app = true
