name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy-cloudflare:
    runs-on: ubuntu-latest
    environment: Cloudflare Workers
    concurrency:
      group: deploy-cloudflare
      cancel-in-progress: false
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'npm'
      - name: Install
        run: npm ci --no-audit --no-fund
      - name: Test
        run: npm t
      - name: Deploy
        run: npm run deploy -- -F cloudflare-app

  deploy-aws:
    runs-on: ubuntu-latest
    environment: AWS
    concurrency:
      group: deploy-aws
      cancel-in-progress: false
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_HANDLER_VERIFY_HEADER: ${{ secrets.AWS_HANDLER_VERIFY_HEADER }}
      AWS_REGION: ${{ vars.AWS_REGION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'npm'
      - name: Install
        run: npm ci --no-audit --no-fund
      - name: Test
        run: npm t
      - name: Deploy
        run: npm run deploy -- -F aws-app -- --require-approval never
